### ISSUE TITLE
Configure gitignore and remove unnecessary and temporary files from git index

### ISSUE THREAD

**Issue by 4unkur** [taalayuulu/Blog#1]
Add content of https://github.com/github/gitignore/blob/master/Symfony.gitignore
to `.gitignore` file.
Also add line `.idea` to it.

Then update your git index by entering following commands:

`git rm -r --cached .`
`git add .`
`git commit -am "Remove ignored files"`

Source: http://stackoverflow.com/questions/1274057/making-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore

**Comment by taalayuulu** [comment]
thanks mate

**Comment by 4unkur** [comment]
You're welcome dude, but you didn't added `.idea` to `.gitignore`
So it still remains in the source

**Comment by taalayuulu** [comment]
I have tried to add it like  [this](https://www.dev-metal.com/how-to-ignore-remove-idea-folder-from-git-in-phpstorm/)  , then I add it manually to ignore file . neyse rahmat
